### PR TITLE
#161044907 Admin can create user profile

### PR DESCRIPTION
**Pull request by Deekerubo**
**What does this PR do?**
This PR creates a user profile for the store attendant.
**Description of Task to be completed?**
An admin canadd new users to the store manager app.
**How should this be manually tested?**
Git clone the repository `git clone https://github.com/Deekerubo/Store-Manager.git` to you local machine then navigate using the admin email and password such as admin@gmail.com and password as admin then to the products section then navigate to the products section.
**Any background context you want to provide?**
This section of the page is only view able by the admin who has the authority to add users to the system
screenshot from 2018-10-12 03-11-46

**What are the relevant pivotal tracker stories?**
#161044907 
**Screenshots (if appropriate)**

### CODE REVIEW

**Comment by lizvin** [comment]
The UI interface looks appealing, proper use of icons, effective colour shades that have a correlation.

**Comment by Teatoller** [comment]
Hi @Deekerubo ,
You are doing well! Would you consider using a different color from the icon for the words below them.

Regards
Steven Ennis

**Comment by Paulvitalis200** [comment]
Nice work.. Maybe add a margin at the bottom section to separate add user from the footer

**Comment by kelvinrandu** [comment]
nice design

**Pull request merged**
