### PR TITLE
#161067062 Create a LogIn page

### PR DESCRIPTION
**Pull request by Deekerubo**
**What does this PR do?**
It Creates a Login page for both he Store attendant and the Store admin.

**Description of Task to be completed?**
The user is able to LogIn using the required Email Address and Password. If the LogIn credentials are false there is an error to the system.
**How should this be manually tested?**
Clone the repository to you local machine then access the page using your local URL to your a browser of your choice. Try  to log in.
**Any background context you want to provide?** 
It is a requirement with the project guidelines that the LogIn credentials should be validated.
**What are the relevant pivotal tracker stories?**
#161067062
**Screenshots (if appropriate)**
screenshot from 2018-10-08 23-37-01

**Questions**
What do you think I should add to my LogIn page?

### CODE REVIEW

**Comment by Nicanor008** [comment]
@Deekerubo Great UI, (claps). Maybe you can just consider how you will redirect store attendant and owner to different pages. Otherwise, you are good to go

**Comment by Teatoller** [comment]
Hi Diana,
I would suggest not to have a Remember me checkbox.
My reasoning is that this application is on a cash machine very likely used by several individuals.
It is likely to make the user prone to their credentials being abused and result in accountability issues.

**Comment by Deekerubo** [comment]
> Hi Diana,
> I would suggest not to have a Remember me checkbox.
> My reasoning is that this application is on a cash machine very likely used by several individuals.
> It is likely to make the user prone to their credentials being abused and result in accountability issues.

Thank you Steve, I've already done away with it.

**Comment by Paulvitalis200** [comment]
Great UI. And I see you have already removed the remember me check box.

**Pull request merged**
