### PR TITLE
#161074591 Store attendant Dashboard

### PR DESCRIPTION
**Pull request by Deekerubo**
**What does this PR do?**
this PR introduces the aspect of the store attendant dashboard. 

**Description of Task to be completed?**
This is the the landing page after the store attendant has logged in. The user navigates by what task they want achieved.

**How should this be manually tested?**
Clone this repository to your local machine, `git clone https://github.com/Deekerubo/Store-Manager.git` then navigate to the login.html page and log in. you will automatically be directed to the dashboard page.

**Any background context you want to provide?**
the page contains navigation links to other pages the Store attendant can navigate.
** What are the relevant pivotal tracker stories?**
#161074591
**Screenshots (if appropriate)**
screenshot from 2018-10-10 13-54-15
**Questions:**
What questions do you have for this PR?

### CODE REVIEW

**Comment by johnwayodi** [comment]
Impressive Design.
The **Profile Picture** element seems to be touching the Browser edge to the left. A suggestion...perhaps giving it some some space from the edge.

**Comment by DennisDaddy** [comment]
Amazing interface...

**Comment by kelvinrandu** [comment]
cool design

**Comment by Teatoller** [comment]
Hello Deekerubo,
You have done some work here. It has a good look feel.

Regards
Steven Ennis

**Pull request merged**
